name: FitHub Project CI
on: 
  push:
    branches: [ main ]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Use Node.js version 19
        uses: actions/setup-node@v3
        with: 
          node-version: "19"
      - run: npm run install
      - run: npm run build --prefix front-end 